# Generated by Django 6.0.4 on 2026-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_emoji', models.CharField(default='🏆', help_text='Single emoji character for the achievement icon', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.CharField(help_text='e.g. "Feb 2026"', max_length=50)),
                ('end_date', models.CharField(help_text='e.g. "Apr 2026" or "Present"', max_length=50)),
                ('bullets', models.TextField(help_text='One bullet point per line. Each line will be displayed as a list item.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first (top of timeline).')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, help_text='Mark as read once reviewed.')),
            ],
            options={
                'verbose_name': 'Hire Request',
                'verbose_name_plural': 'Hire Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated technologies, e.g. "Django, REST API, JavaScript"', max_length=500)),
                ('github_url', models.URLField(blank=True, default='#')),
                ('demo_url', models.URLField(blank=True, default='#')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or preview image (800x450px recommended)', null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=True, help_text='Featured projects appear first in the grid.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('date_label', models.CharField(blank=True, default='', help_text='Display date label, e.g. "July 2025"', max_length=50)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, help_text='Upload the resume PDF here. Will be served as Shikhar_Kanaujia_Resume.pdf', null=True, upload_to='resume/')),
                ('about_bio', models.TextField(default='', help_text='The bio text that appears in the About section.')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/shikhar-kanaujia', help_text='Full LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, default='https://github.com/shikhar-kanaujia', help_text='Full GitHub profile URL')),
                ('meta_description', models.CharField(default='Shikhar Kanaujia — Software Engineer, AI Builder, CS @ IIIT Sonepat.', help_text='Meta description for SEO (max 300 chars)', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frameworks & Tools', 'Frameworks & Tools'), ('AI/ML', 'AI/ML'), ('Databases', 'Databases'), ('Concepts', 'Concepts')], default='Languages', max_length=50)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
            },
        ),
    ]
