# Generated by Django 6.0.4 on 2026-05-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Company logo image (square aspect ratio recommended)', null=True, upload_to='company_logos/'),
        ),
    ]
