# Generated by Django 5.2.13 on 2026-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_achievement_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Or upload a certificate file (PDF/Image)', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='certificate_link',
            field=models.URLField(blank=True, default='', help_text='Link to the certificate (e.g., credential URL or Drive link)'),
        ),
    ]
