# Generated by Django 6.0.4 on 2026-05-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_certificate_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Twitter, Instagram', max_length=50)),
                ('url', models.URLField(help_text='Full URL to the social profile')),
                ('icon_image', models.ImageField(help_text='Upload icon image here', upload_to='social_icons/')),
                ('order', models.IntegerField(default=0)),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='portfolio.siteconfig')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
